(
	messageBox "Layer Manager Extension v2.0 has now been installed!
	\n\nTo set it up go to:
	\n1/ Run 3dsMax as Administrator
	\n2/ Scripting -> Run script... -> Run Setup.mzp  
	\n3/ Menu-> Customize -> Customize Interface... -> Toolbars
	\n4/ Category: 'ArchvizTools' and drag 'Layer Manager Extension' to a toolbar
	\n5/ Click the toolbar icon to run the script.
	\n\n---
	\n© ArchvizTools" title:"Script installer message" beep: false
)